fix(deps): update ktor monorepo to v3.1.0 (#196)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[io.ktor:ktor-server-test-host](https://redirect.github.com/ktorio/ktor)
| `3.0.3` -> `3.1.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-test-host/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-test-host/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-test-host/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-test-host/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-auth](https://redirect.github.com/ktorio/ktor) |
`3.0.3` -> `3.1.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-auth/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-auth/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-auth/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-auth/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-core](https://redirect.github.com/ktorio/ktor) |
`3.0.3` -> `3.1.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-core/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-core/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-core/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-core/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-netty](https://redirect.github.com/ktorio/ktor) |
`3.0.3` -> `3.1.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-netty/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-netty/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-netty/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-netty/3.0.3/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>ktorio/ktor (io.ktor:ktor-server-test-host)</summary>

###
[`v3.1.0`](https://redirect.github.com/ktorio/ktor/blob/HEAD/CHANGELOG.md#310)

[Compare
Source](https://redirect.github.com/ktorio/ktor/compare/3.0.3...3.1.0)

> Published 11 February 2025

##### Features

- Add reconnection in ClientSSESession
([KTOR-6242](https://youtrack.jetbrains.com/issue/KTOR-6242))
- Add heartbeat to SSE
([KTOR-7908](https://youtrack.jetbrains.com/issue/KTOR-7908))
- Add serialization for SSE
([KTOR-7435](https://youtrack.jetbrains.com/issue/KTOR-7435))
- Support WebSockets in Curl engine
([KTOR-5199](https://youtrack.jetbrains.com/issue/KTOR-5199))
- Support conversion between byte channel interfaces and kotlinx-io
primitives ([KTOR-7327](https://youtrack.jetbrains.com/issue/KTOR-7327))
- Support CIO server on WasmJS and JS targets
([KTOR-865](https://youtrack.jetbrains.com/issue/KTOR-865))
- Logging: Format log like OkHttp client does
([KTOR-7806](https://youtrack.jetbrains.com/issue/KTOR-7806))
- Support static linking for curl on all platforms
([KTOR-6754](https://youtrack.jetbrains.com/issue/KTOR-6754))
- Support ARM target in Ktor client with Kotlin/Native and Curl
([KTOR-4570](https://youtrack.jetbrains.com/issue/KTOR-4570))
- Unix Domain Socket Support for Native Targets
([KTOR-6960](https://youtrack.jetbrains.com/issue/KTOR-6960))
- Support receiving multipart data with Ktor client
([KTOR-6632](https://youtrack.jetbrains.com/issue/KTOR-6632))
- Client CIO engine support for wasm-js and js
([KTOR-7675](https://youtrack.jetbrains.com/issue/KTOR-7675))
- Support NodeJs target for ktor-network
([KTOR-6004](https://youtrack.jetbrains.com/issue/KTOR-6004))

##### Improvements

- Auth: BasicAuthProvider caches credentials until process death
([KTOR-7775](https://youtrack.jetbrains.com/issue/KTOR-7775))
- CallLogging: Unhelpful log output "Application started: ..."
([KTOR-7797](https://youtrack.jetbrains.com/issue/KTOR-7797))
- Add operator contains to ContentType objects
([KTOR-8145](https://youtrack.jetbrains.com/issue/KTOR-8145))
- Darwin: Ambiguous DarwinHttpRequestException for SSL Pinning failure
([KTOR-6759](https://youtrack.jetbrains.com/issue/KTOR-6759))
- Introduce ServerSocket.port to simplify port access for the bound
server ([KTOR-8136](https://youtrack.jetbrains.com/issue/KTOR-8136))
- Java, Js, Darwin: Response header Sec-WebSocket-Protocol is missing
([KTOR-6970](https://youtrack.jetbrains.com/issue/KTOR-6970))
- Fail to parse url: file:/path/to/file.txt
([KTOR-6709](https://youtrack.jetbrains.com/issue/KTOR-6709))
- Auth: Make re-auth/refresh status codes configurable
([KTOR-7644](https://youtrack.jetbrains.com/issue/KTOR-7644))
- Add media type for Yaml
([KTOR-8064](https://youtrack.jetbrains.com/issue/KTOR-8064))
- Logging: HTTP method is logged with the class name
([KTOR-8011](https://youtrack.jetbrains.com/issue/KTOR-8011))
- Uncaught cannot write to a channel errors from ws-pinger
([KTOR-8008](https://youtrack.jetbrains.com/issue/KTOR-8008))
- Apache5 client: Upgrade HttpClient to 5.4
([KTOR-8080](https://youtrack.jetbrains.com/issue/KTOR-8080))
- Swagger: Add deepLinking configuration
([KTOR-8074](https://youtrack.jetbrains.com/issue/KTOR-8074))
- Access to the configuration options of a HttpClient plugin to tweak or
wrap them with additional logic
([KTOR-7213](https://youtrack.jetbrains.com/issue/KTOR-7213))
- Don't publish internal test artifacts
([KTOR-8058](https://youtrack.jetbrains.com/issue/KTOR-8058))
- Micrometer: Add UptimeMetrics to standard meterBinders
([KTOR-8061](https://youtrack.jetbrains.com/issue/KTOR-8061))
- MicrometerMetrics: Do not write unknown HTTP method names to metrics
([KTOR-7658](https://youtrack.jetbrains.com/issue/KTOR-7658))
- Update to Kotlin 2.1.0
([KTOR-7866](https://youtrack.jetbrains.com/issue/KTOR-7866))
- ByteWriteChannel is missing writeFloat()/readFloat()
([KTOR-7651](https://youtrack.jetbrains.com/issue/KTOR-7651))
- Engine exclusion from clientTests is confusing
([KTOR-7723](https://youtrack.jetbrains.com/issue/KTOR-7723))
- UrlBuilder: Support telephone scheme
([KTOR-4816](https://youtrack.jetbrains.com/issue/KTOR-4816))
- Swagger UI: Missing Favicon while browsing the UI
([KTOR-7893](https://youtrack.jetbrains.com/issue/KTOR-7893))
- ContentNegotiation client plugin: no way to opt out of Accept on a
per-request basis
([KTOR-7722](https://youtrack.jetbrains.com/issue/KTOR-7722))
- `receiveMultipart` throws IllegalStateException instead of
UnsupportedMediaTypeException
([KTOR-7470](https://youtrack.jetbrains.com/issue/KTOR-7470))
- Implement a suspending version of EmbeddedServer.start(wait=true)
([KTOR-7459](https://youtrack.jetbrains.com/issue/KTOR-7459))
- Allow to Disable Body Decompression on the Server for a specific call
([KTOR-7679](https://youtrack.jetbrains.com/issue/KTOR-7679))
- UDPSocketBuilder missing `bind` overload with `hostName` and `port`
([KTOR-7663](https://youtrack.jetbrains.com/issue/KTOR-7663))
- Make Url class
[@&#8203;Serializable](https://redirect.github.com/Serializable) and JVM
Serializable
([KTOR-7620](https://youtrack.jetbrains.com/issue/KTOR-7620))
- Improve parsing of supported media types (MIME types)
([KTOR-7586](https://youtrack.jetbrains.com/issue/KTOR-7586))
- Migrate to kotlin.AutoCloseable
([KTOR-7606](https://youtrack.jetbrains.com/issue/KTOR-7606))

##### Bugfixes

- ByteChannel read issue on min > 1
([KTOR-8172](https://youtrack.jetbrains.com/issue/KTOR-8172))
- CIO Server Engine fails for requests with more than 64 headers
([KTOR-8164](https://youtrack.jetbrains.com/issue/KTOR-8164))
- OutOfMemoryError when sending a large binary file through
ByteReadChannel converted from InputStream
([KTOR-6185](https://youtrack.jetbrains.com/issue/KTOR-6185))
- Native Windows tests failing due to port exhaustion
([KTOR-7392](https://youtrack.jetbrains.com/issue/KTOR-7392))
- Unable to close socket with open read/write channels on Native
([KTOR-8144](https://youtrack.jetbrains.com/issue/KTOR-8144))
- Jetty idleTimeout not working
([KTOR-8138](https://youtrack.jetbrains.com/issue/KTOR-8138))
- Fix concurrent flush and close in the reader
([KTOR-8133](https://youtrack.jetbrains.com/issue/KTOR-8133))
- Socket.accept doesn't throw an exception on closing a socket on Native
([KTOR-8135](https://youtrack.jetbrains.com/issue/KTOR-8135))
- "AbortError: BodyStreamBuffer was aborted" error when canceling parent
job ([KTOR-7734](https://youtrack.jetbrains.com/issue/KTOR-7734))
- Race condition when writing to a buffer leads to NPE inside
CIOReaderKt.readFrom
([KTOR-8105](https://youtrack.jetbrains.com/issue/KTOR-8105))
- ArrayIndexOutOfBounds kotlinx-io
([KTOR-8096](https://youtrack.jetbrains.com/issue/KTOR-8096))
- NPE in readBuffer
([KTOR-8086](https://youtrack.jetbrains.com/issue/KTOR-8086))
- JS/WASM fails with "IllegalStateException: Content-Length mismatch" on
requesting gzipped content
([KTOR-7934](https://youtrack.jetbrains.com/issue/KTOR-7934))
- SessionStorage.read() is called for non-authenticated routes and
static assets
([KTOR-7194](https://youtrack.jetbrains.com/issue/KTOR-7194))
- Read mutipart upload regression from 2.x to 3.x
([KTOR-8082](https://youtrack.jetbrains.com/issue/KTOR-8082))
- HttpRequestRetry: race condition for isClosedForRead leads to
EOFException: Channel is already closed
([KTOR-8051](https://youtrack.jetbrains.com/issue/KTOR-8051))
- ktor-client-curl artifacts aren’t published after EAP 1146
([KTOR-8091](https://youtrack.jetbrains.com/issue/KTOR-8091))
- DoubleReceive: NullPointerException caused by race condition
([KTOR-8045](https://youtrack.jetbrains.com/issue/KTOR-8045))
- Uncaught ClosedWatchServiceException exception thrown by finalizer
when closing the server
([KTOR-7963](https://youtrack.jetbrains.com/issue/KTOR-7963))
- Curl: Error linking curl in linkDebugExecutableLinuxX64 on macOS
([KTOR-6361](https://youtrack.jetbrains.com/issue/KTOR-6361))
- ktor-server-core: Test files are part of the distribution code
([KTOR-8003](https://youtrack.jetbrains.com/issue/KTOR-8003))
- Windows: undefined symbols in linker when ktor-client-curl is used
([KTOR-4307](https://youtrack.jetbrains.com/issue/KTOR-4307))
- SaveBodyPlugin: UninitializedPropertyAccessException when reading
response body within receivePipeline
([KTOR-7952](https://youtrack.jetbrains.com/issue/KTOR-7952))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/stuebingerb/KGraphQL).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNjQuMSIsInVwZGF0ZWRJblZlciI6IjM5LjE2Ny4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>